### ISSUE TITLE
Idea for fixing a bug

### ISSUE THREAD

**Issue by PipSqick** [ficool2/HammerPlusPlus-Website#10]
[CS:GO] Hammer++ breaks when opening a menu with props. I think this is due to props not working. This can be fixed by deleting them from the models folder. But I don't know how to understand which prop is working and which one will cause the program to crash. If this can be prevented, that would be cool. Maybe props just don't show up on the menu? Or make a dedicated scan button?

![2022-01-26_01-02-20](https://user-images.githubusercontent.com/49367430/151043024-9fcaad43-1fc5-4e3b-b03c-6fd667c3d447.png)

**Comment by ficool2** [comment]
Hammer++ will now show which model is causing the crash in Build 8858
