### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION on startup

### ISSUE THREAD

**Issue by DarkCookieSF** [ficool2/HammerPlusPlus-Website#109]
I keep getting the error EXCEPTION_ACCESS_VIOLATION with the address "vguimatsurface.dll!0xAFA6"

I have tried everything, I reinstalled Hammer++, I verified the integrity of my game files, with and without the file in the games files, I reinstalled Garry's Mod. Nothing works, so that's why I'm making this issue. 

Here's the error:
![image](https://github.com/user-attachments/assets/b034f7b9-0696-4657-b88f-4b0fe651016d)

Here's the log:
[hammerplusplus_20241116_141705_1_x0000000053F2E5C8.zip](https://github.com/user-attachments/files/17787985/hammerplusplus_20241116_141705_1_x0000000053F2E5C8.zip)

**Comment by ficool2** [comment]
Reinstall Hammer++ from the website, if it's erroring then you did not reinstall it correctly
