### ISSUE TITLE
Why 32 bit?

### ISSUE THREAD

**Issue by ultimateshadsform** [ficool2/HammerPlusPlus-Website#113]
Is there a reason for only making 32 bit and not 64?

![image](https://github.com/user-attachments/assets/69428eb2-51a3-4579-a8b8-442c7ed5c049)

**Comment by dk865** [comment]
Yes- Source Games are only 32 bit, along with regular hammer, so it is pretty much impossible to make it 64 bit without source code, and is also pointless, unless someone decides to make a 64 bit source game, with the public 2013 source.

**Comment by ultimateshadsform** [comment]
Oh okay
