### ISSUE TITLE
Hammer ++ Portal 1&2

### ISSUE THREAD

**Issue by LegionInstaller** [ficool2/HammerPlusPlus-Website#16]
Hello ficool2 I just wanted to ask if there will be a standalone version for the Portal series just out of curiosity 
I'm sorry I have to write it in form as an Issue but I haven't found another way to contact you 
Thank you for your Understanding

**Comment by TheBlokker** [comment]
ok, for Portal 1 you can use the ("2013 Single Player") Version.
Portal 2, see  [here](https://steamcommunity.com/sharedfiles/filedetails/?id=2742731712)
have a nice day. 😄

**Comment by TheBlokker** [comment]
you can wirte it in [HammerPlusPlus-Issue-Tracker](https://github.com/ficool2/HammerPlusPlus-Issue-Tracker)
