### ISSUE TITLE
Monitor alignment messed up.

### ISSUE THREAD

**Issue by Werru2955** [ficool2/HammerPlusPlus-Website#3]
Last night, I was making a monitor in my map, and I noticed something weird happening. When I selected fit in the texture tools for any of the monitor textures (I tried dev_tvmontior1b, and dev_tvmonitor1a, as well as dev_combinemonitor_1)
![image](https://user-images.githubusercontent.com/65135562/112991974-bc194900-9135-11eb-8384-a187fadbcdc8.png)
it would come out in the engine looking like this
![image](https://user-images.githubusercontent.com/65135562/112992375-1d411c80-9136-11eb-811e-25decf7a501b.png)
So, the next idea I had was to create a 256x256 alignment image, align it, switch it back to the monitor texture, and try it in the engine.
![image](https://user-images.githubusercontent.com/65135562/112992744-7610b500-9136-11eb-9d84-f3618bad62b4.png)
So I aligned it like this, and then switched it to the monitor texture dev_tvmonitor1b, and in the engine, it looked like this...
![image](https://user-images.githubusercontent.com/65135562/112992940-a8baad80-9136-11eb-8c9f-75c4013855b7.png)
So the next thing I did was look at the texture properties for the monitor and...
![image](https://user-images.githubusercontent.com/65135562/112993015-bcfeaa80-9136-11eb-9aac-b57717c1163f.png)
these aren't the numbers I originally inputted.

I'm running Windows 10 LTSC 2019, with all the latest security patches, and an aero theme (though I doubt that could interfere) and am on hammer++ build 8849

If you could take a look at my report, I would appreciate it

Thanks,
Werru2955

**Comment by localmanislocal** [comment]
I've been having this exact same issue since last year. My temporary fix (until it is patched for H++) is to just fit the texture & compile the map in regular Hammer.

Sorry I can't help you - just wanted to add another voice to this specific bug as it drives me nuts!

**Comment by ficool2** [comment]
Fixed in build 8858.
Use https://github.com/ficool2/HammerPlusPlus-Issue-Tracker in the future
