### ISSUE TITLE
Can't put a comma in IO System in non-CS:GO games, output gets offset after restarting Hammer or map compile

### ISSUE THREAD

**Issue by 8BEATER-Il-S** [ficool2/HammerPlusPlus-Website#32]
### Describe the bug
The .VMF file stores wrong data about an output which contains a comma, which makes passing functions with multiple parameters through VScript quite troublesome in non-CS:GO games. It's noticeable only after saving the file and restarting Hammer++.
This bug also breaks logic on compile and doesn't produce any errors in compile and game consoles.

### Steps to reproduce
1. Have an output which contains a comma, like this one: 
![изображение](https://user-images.githubusercontent.com/80397331/182920787-84cea077-d2d6-43f8-b638-b0e499253a79.png)
2. Restart Hammer++.
3. See the parameter be transferred over to the delay and fires limit. ![изображение](https://user-images.githubusercontent.com/80397331/182921087-5a56ae68-6484-4e68-9244-b8d410fd93f7.png)

### Expected behavior
Have parameters look fine like on the first screenshot. If it's a feature, then at least give a warning and an option to disable it, because the way it is now won't cut it.
![изображение](https://user-images.githubusercontent.com/80397331/182929204-592fc16d-3b9e-45fd-b5e7-18e8ba983955.png)
![изображение](https://user-images.githubusercontent.com/80397331/182929946-1e8f5a0e-a333-4eaa-9314-b9775c3e6934.png)

**Comment by 8BEATER-Il-S** [comment]
Sorry if this sounded way too aggressive, I was just angry at the moment, I don't mean any hate. I really appreciate this work on Hammer++, but this issue just got me by surprise and I spent about an hour on this before figuring it out. Still, I think there needs to be at least a warning.

**Comment by hexaflexahexagon** [comment]
I'll let someone smarter confirm/deny but I'm fairly sure this is just a limitation with the vmf file format in older engine games and can't be worked around without breaking backwards compatibility.
