### ISSUE TITLE
Ultimate Mapping Resource Pack Support?

### ISSUE THREAD

**Issue by HatWearingMann** [ficool2/HammerPlusPlus-Website#57]
Hello, is there a way to use the "[Ultimate Mapping Resource Pack](https://tf2maps.net/downloads/ultimate-mapping-resource-pack.510/)" for hammer++? 

The improved FGD isn't working.

**Comment by hexaflexahexagon** [comment]
that pack is very old and superseded by hammer++, you don't need to use it
