### ISSUE TITLE
Collision model colour not correct in 2d views. (Original hammer quirk)

### ISSUE THREAD

**Issue by 111112oo** [ficool2/HammerPlusPlus-Website#8]
![image](https://user-images.githubusercontent.com/11363514/150666066-44080562-f06b-4c57-aeb5-4399fbb1b3fb.png)
When the "Shows collision model wireframe" button is selected, enabled collision models have a yellow wireframe and disabled ones have a purple wireframe. This shows correctly in the 3d view, but shows all collision models as yellow in the 2d view. This quirk is present in original hammer. The opposite happens on dynamic models as it seems to take the colour of the model box that appears when you are too far away in either view.

**Comment by ficool2** [comment]
https://github.com/ficool2/HammerPlusPlus-Issue-Tracker
